spring.application.name=activity-service

spring.config.import=optional:configserver:http://localhost:8888

#Retry Configurations

#resilience4j.retry.instances.userServiceRetry.max-attempts=3    Retry the request a maximum of 3 times if a retryable exception occurs.
#resilience4j.retry.instances.userServiceRegistry.wait-duration=2s  Wait 2 seconds between each retry attempt.


#resilience4j.retry.instances.userServiceRetry.retry-exceptions=\
#org.springframework.web.reactive.function.client.WebClientRequestException,\
#java.net.ConnectException,\
#java.net.SocketTimeoutException
#============================================= explaination of the upper 3 java.net and these
#Retry only when these exceptions occur (network/connectivity-related failures).
#
#WebClientRequestException → Retry if the WebClient cannot send the request due to network issues.
#ConnectException → Retry if the connection to the target service cannot be established.
#SocketTimeoutException → Retry if the request times out while waiting for a response.
#==============================================================================



#resilience4j.retry.instances.userServiceRetry.ignore-exceptions=\
#org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest,\
#org.springframework.web.reactive.function.client.WebClientResponseException$Unauthorized,\
#org.springframework.web.reactive.function.client.WebClientResponseException$NotFound
##===========================
#Do not retry when these exceptions occur because they are client/business errors.
#
#BadRequest (400) → Request is invalid; retrying won't fix it.
#Unauthorized (401) → Authentication failed; retrying without valid credentials is useless.
#NotFound (404) → Requested resource doesn't exist; retrying won't make it exist.
#================================
